articles/urls.py
from django.urls import path 
from articles import views   #read views

app_name = "articles"
urlpatterns = [
    path('' , views.articleslist , name = "list"),
    path('<slug>' , views.article_detail , name = "detail"),
]

djangonew/urls.py
from django.contrib import admin
from django.urls import path , include 
from djangonew import views   #read views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/' , admin.site.urls),
    path('about/' , views.about),
    path('' , views.home),
    path('articles/' , include('articles.urls'))
]

urlpatterns += staticfiles_urlpatterns()   # ezafe kardane ye

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 50)
    slug  = models.SlugField()
    body  = models.TextField()
    date  = models.DateTimeField(auto_now_add = True)
    # picture
    # author  # nevisandeh
    def __str__(self):
        return self.title

    def snippet(self):
        return self.body

articles/views.py
from django.shortcuts import render , HttpResponse
from articles import models

# Create your views here.

def articleslist(request):

    articles = models.Article.title
    return render(request, 'articles/articleslist.html', {'articles':articles})

def article_detail(request , slug):
    
    return HttpResponse(slug)

djangonew/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

def about(request):
    return render(request , 'about.html')


def home(request):
    return render(request , 'home.html')  

articles/templates/articles/articleslist.html
{% extends 'base.html' %}
 {% block title %}
 Articles
 {% endblock  %}

{% block content %}
       
    <div class = "container"> 
       <h1> Articles list </h1>
        {% for article in Articles %} 
        <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{Article.title}}</a></h2>
        {% comment %} <p>{{Article.snippet}}</p>
        <p>{{Article.date}}</p> {% endcomment %}
        {% endfor %}
    </div>
     {% endblock   %}